# Generated by Django 3.2.5 on 2021-08-02 19:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='address',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
        migrations.AddField(
            model_name='customer',
            name='balance',
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AddField(
            model_name='customer',
            name='pickup_day',
            field=models.CharField(default='Monday', max_length=9),
        ),
        migrations.AddField(
            model_name='customer',
            name='suspend_end',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='customer',
            name='suspend_start',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='customer',
            name='zipcode',
            field=models.CharField(default='', max_length=5),
        ),
    ]
