# Generated by Django 3.2.5 on 2021-08-03 14:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0001_initial'),
        ('customers', '0002_auto_20210802_1459'),
    ]

    operations = [
        migrations.CreateModel(
            name='CompletedPickup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(editable=False)),
                ('customer', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.PROTECT, to='customers.customer')),
                ('employee', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.PROTECT, to='employees.employee')),
            ],
        ),
    ]
