# Generated by Django 3.2.5 on 2021-08-03 16:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0004_special_pickups'),
    ]

    operations = [
        migrations.RenameField(
            model_name='special_pickups',
            old_name='date',
            new_name='special_pickup_date',
        ),
    ]
