# Generated by Django 3.2.5 on 2021-08-03 16:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0005_rename_date_special_pickups_special_pickup_date'),
    ]

    operations = [
        migrations.RenameField(
            model_name='special_pickups',
            old_name='customer',
            new_name='customer_id',
        ),
    ]
