# Generated by Django 3.2.5 on 2021-08-03 16:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0006_rename_customer_special_pickups_customer_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='special_pickups',
            old_name='customer_id',
            new_name='customer',
        ),
    ]
