# Generated by Django 3.2.5 on 2021-08-04 16:42

from django.db import migrations
from employees.models import Employee
from accounts.models import User

def create_dummy_data(apps, schema_editor):
    # Employee = apps.get_model('employees', 'Employee')
    # User = apps.get_model('accounts', 'User')
    Employee.objects.all().delete()

    # Need to get all the existing users with id < 20
    created_users = User.objects.all()
    created_users = created_users[:20]

    # 20 sets of data for the employees
    # Name (string), zipcode (string), user(User)
    employees_data = [
        ['Abdul Audia', '80911'],
        ['Barrett Booker', '80911'],
        ['Apryl Flagg', '80911'],
        ['Waneta Pamplin', '80911'],
        ['Tad Chipman', '80911'],
        ['Bev Thronson', '27540'],
        ['Eugene Gladden', '27540'],
        ['Elnora Nolin', '27540'],
        ['Emmie Shuck', '27540'],
        ['Julius Edling', '27540'],
        ['Brendan Dubuc', '19050'],
        ['Myrna Feingold', '19050'],
        ['Stasia Frailey', '19050'],
        ['Joellen Wester', '19050'],
        ['Sherryl Cronan', '19050'],
        ['Trang Illingworth', '45011'],
        ['Elwood Statham', '45011'],
        ['Alta Dygert', '45011'],
        ['Catrina Rolfe', '45011'],
        ['Tarsha Slovak', '45011'],
    ]

    for i in range(len(created_users)):
        current_employee = Employee(name=employees_data[i][0], zipcode=employees_data[i][1], user=created_users[i])
        current_employee.save()
    

class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0001_initial'),
        ('accounts', '0002_auto_20210804_1142')
    ]

    operations = [
        migrations.RunPython(create_dummy_data)
    ]
